### ISSUE TITLE
Questions about how to build & run Dryad

### ISSUE THREAD

**Issue by hehaifengcn** [MicrosoftResearch/Dryad#4]
Hi
I have a couple of questions:
1. In the README.txt, in "Building Dryad" section, I wasn't sure about how to follow step
   (5) Run Build.bat in the Java directory at the top-level of the repository.  
   I couldn't find "build.bat" in the repos.
2. Any instruction on how to run Dryad? I saw there is a Samples directory but have no idea how to run it.

Thanks
Haifeng

**Comment by fetterly** [comment]
Hi Haifeng,

Thank you for your interest in Dryad.  The README.txt file is out of date, unfortunately.  We will push an update shortly.  Fortunately,the process is now much simpler.

If you just want to run a sample DryadLINQ program, the simplest way to get started is to follow the instructions in the GitHub wiki at https://github.com/MicrosoftResearchSVC/Dryad/wiki/Getting-started-with-DryadLINQ.

If you want to run a version you build, the following steps should work:
1) Clone the Dryad git repository.
2) Set the DRYAD_HOME environment variable to binary path
   (bin\Debug or bin\Release) under the directory Dryad was cloned to.
3) Use Visual Studio to open The Dryad solution file (Dryad.sln) located 
   in the root of the repository and build the solution.  The dependencies
   will be fetched from NuGet.
4) Build and compile your program, referencing the Microsoft.Research.DryadLINQ dll.  

-Dennis

**Comment by hehaifengcn** [comment]
Thanks, Dennis. I was able to run the sample project following the Wik instruction.
